package inkspire.morphic.feature.settings.about

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Where the open-source manifest comes from — **an interface here, implemented in `:app`.**
 *
 * The manifest is generated by the AboutLibraries Gradle plugin from the *application's* resolved dependency graph,
 * which is the only graph that describes what actually ships, so it lands in `:app`'s resources and nowhere else. A
 * library module cannot name another module's `R`, and the two ways out of that are not equal:
 * `Resources.getIdentifier` would resolve it by name, and a resource referenced only by name is one `shrinkResources`
 * is free to delete from the release build — a screen that is full in debug and empty in the APK users install.
 * Reaching it through the composition root instead makes the reference `R.raw.aboutlibraries`, which is a **compile
 * error** when it is missing rather than an empty list at runtime.
 *
 * Not suspending: the implementation reads a resource that is already in the APK. Getting it *off the main thread* is
 * the caller's business, and [LicensesViewModel] does that around the parse, which is the expensive half anyway.
 */
fun interface LicenseManifestSource {
    /** The manifest, as the JSON the build wrote. */
    fun readJson(): String
}

/**
 * One open-source library the app ships, as the screen shows it.
 *
 * Every field here came out of the artifact's own POM at build time — none of it is typed by hand anywhere in this
 * repo, which is the entire claim the licenses screen makes.
 *
 * @property coordinates the Maven `group:artifact`. Shown because it is the identifier you can actually look up; a
 *   display name like "Activity" or "collections" is not searchable on its own.
 * @property author the publishing organization, falling back to the first named developer. Null where the POM gives
 *   neither — the Compose BOM is the one such artifact today, being a version list rather than code.
 * @property licenses every license the artifact is offered under. A list because dual-licensing is real, though
 *   nothing in this graph currently uses it.
 */
internal data class OpenSourceLibrary(
    val name: String,
    val coordinates: String,
    val version: String?,
    val author: String?,
    val website: String?,
    val licenses: List<OpenSourceLicense>,
)

/**
 * A license, deduplicated across every library offered under it.
 *
 * **One entry per license, not per library**, which is the shape the manifest already has and the shape the screen
 * needs: 144 libraries resolve to two licenses here, so attaching the full Apache text to each row would put the same
 * eleven thousand characters on screen 140 times.
 *
 * @property text the full license text, carried in the APK. Null only if the build excluded `content` — see the
 *   `aboutLibraries { export { } }` block in `app/build.gradle.kts`, which deliberately keeps it.
 */
internal data class OpenSourceLicense(
    val id: String,
    val name: String,
    val url: String?,
    val text: String?,
)

/**
 * The parsed manifest: every library, and the distinct licenses they are offered under.
 *
 * @property libraries sorted by display name, case-insensitively — the order the screen shows and the only order that
 *   makes a list of this length scannable. Sorting here rather than in the composable keeps the pane a renderer.
 * @property licenses the distinct licenses actually in use, sorted by name. Derived from [libraries] rather than from
 *   the manifest's own license map: the map holds every license the plugin *knows*, and a license nothing in the graph
 *   uses would be a claim about this app that is not true of it.
 */
internal data class LicenseIndex(
    val libraries: List<OpenSourceLibrary>,
    val licenses: List<OpenSourceLicense>,
) {
    companion object {
        val Empty = LicenseIndex(emptyList(), emptyList())
    }
}

/**
 * Parses the manifest the build generated.
 *
 * `ignoreUnknownKeys` because the plugin's schema is the plugin's: it carries `scm`, `tag` and per-artifact fields
 * this screen does not show, and a new one appearing in a version bump must not turn the licenses screen into an
 * exception. The fields that *are* read are all optional here for the same reason — an artifact whose POM omits its
 * website is listed without one rather than dropped.
 */
internal fun parseLicenseManifest(json: String): LicenseIndex {
    val manifest = ManifestJson.Format.decodeFromString<ManifestJson>(json)
    val licenses = manifest.licenses.mapValues { (id, license) ->
        OpenSourceLicense(
            id = id,
            name = license.name ?: license.spdxId ?: id,
            url = license.url?.takeIf { it.isNotBlank() },
            text = license.content?.takeIf { it.isNotBlank() },
        )
    }
    val libraries = manifest.libraries.map { library ->
        OpenSourceLibrary(
            name = library.name ?: library.uniqueId,
            coordinates = library.uniqueId,
            version = library.artifactVersion?.takeIf { it.isNotBlank() },
            // The organization is the copyright holder where the POM names one; a developer is the fallback, and is
            // what most AndroidX artifacts actually carry.
            author = library.organization?.name?.takeIf { it.isNotBlank() }
                ?: library.developers.firstNotNullOfOrNull { it.name?.takeIf(String::isNotBlank) },
            website = library.website?.takeIf { it.isNotBlank() },
            licenses = library.licenses.mapNotNull(licenses::get).sortedBy { it.name },
        )
    }.sortedBy { it.name.lowercase() }

    return LicenseIndex(
        libraries = libraries,
        licenses = libraries.flatMap { it.licenses }.distinctBy { it.id }.sortedBy { it.name },
    )
}

/** The manifest as the AboutLibraries plugin writes it. Private: nothing outside this file speaks its schema. */
@Serializable
private data class ManifestJson(
    val libraries: List<LibraryJson> = emptyList(),
    val licenses: Map<String, LicenseJson> = emptyMap(),
) {
    companion object {
        val Format = Json { ignoreUnknownKeys = true }
    }
}

@Serializable
private data class LibraryJson(
    val uniqueId: String,
    val artifactVersion: String? = null,
    val name: String? = null,
    val website: String? = null,
    val developers: List<DeveloperJson> = emptyList(),
    val organization: OrganizationJson? = null,
    @SerialName("licenses") val licenses: Set<String> = emptySet(),
)

@Serializable
private data class DeveloperJson(val name: String? = null)

@Serializable
private data class OrganizationJson(val name: String? = null)

@Serializable
private data class LicenseJson(
    val name: String? = null,
    val url: String? = null,
    val content: String? = null,
    val spdxId: String? = null,
)
